# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180618_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='menu',
            name='created_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='menu',
            name='expiration_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
