# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-19 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_change_datetime_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='expiration_date',
        ),
    ]
